### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/angular-timeseries-chart#1]
### Goal

Create an angular directive that takes an ng-model and use c3js to create a chart.

Example repo: https://github.com/firstandthird/angular-barchart
Data: `example/data.json`

### Tasks
- [ ] angular directive to render out a timeseries chart - http://c3js.org/samples/timeseries.html
- [ ] vertical lines for week ago, 2 weeks ago, 3 weeks ago, 4 weeks ago
- [ ] horizontal line for average
- [ ] horizontal line for max
- [ ] horizontal line for min
